# 应用名称
spring:
  application:
    name: RabbitMQ-Consumer

  rabbitmq:
    host: 192.168.150.101  # 主机
    port: 5672             # 端口，5672一般用于信息传递，15672用于web管理
    username: admin        # 用户名
    password: admin        # 密码
    virtual-host: /        # 虚拟主机，可不设置

    # Work Queue 任务模型添加配置：
    listener:
      simple:
        prefetch: 1  # 每次只能获取一条消息，处理完成才能获取下一个消息

server:
  port: 8082


